version: '3.3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'search_engine'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-sql-db:/var/lib/mysql
# Names our volume
volumes:
  my-sql-db: