server:
  port: 8080

# уровень логирования для запуска в режиме отладки
#logging:
#  level:
#    searchengine: DEBUG

spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
# для запуска в режиме отладки
#    show-sql: true

indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: Интернет магазин PlayBack.ru
    - url: https://volochek.life/
      name: Портал www.volochek.life

#    - url: https://et-cetera.ru/mobile/
#      name: МОСКОВСКИЙ ТЕАТР «ET CETERA»

#    - url: http://cimus.biz/
#      name: Цимус
#    - url: https://nopaper.ru/
#      name: Nopaper


java:
  concurrent:
    corePoolSize: 10
    maximumPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
